language: ruby
sudo: false
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=true
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=true
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.8.5" STRICT_VARIABLES=true
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3.8.5" STRICT_VARIABLES=true FUTURE_PARSER="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.5.0" STRICT_VARIABLES=true
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.7.0" STRICT_VARIABLES=true
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.8.0" STRICT_VARIABLES=true
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=true
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.10.4" STRICT_VARIABLES=true

deploy:
  provider: puppetforge
  user: abstractit
  password:
    secure: ZbtzOD15CmlaLJ0zK2qwLLaqXDk+Ile/2nGwZQ3pV5+cx6ILBVHN/cH0PaddVM9z2bV8k/sHN9ZCe5NXEyC54Vta8jCgLvIckS0tRqNICagn5BMhyEg5jSP7IIDhM9pWgF9KiJyMtx+8iWIt6h7v5+HbOylUuSUyhA0ewpFp2GA=
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    rvm: 2.1.9
    condition:
    - $PUPPET_GEM_VERSION = '4.10.4'
    - $STRICT_VARIABLES = true
